dataset_path: ./data/dataset.csv
date_column: DATE
target_column: TOTAL_SOLD
time_input_length: 10
forecast_horizon: 7
model_type: xgboost
model_params:
  learning_rate: 0.1
  max_depth: 3
  n_estimators: 200